# This config file for Travis CI utilizes ros-industrial/industrial_ci package.
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst
services:
  - docker
language: generic

branches:
  except:
   - gh-pages

env:
  global:
    - VERBOSE_OUTPUT=true
    - AFTER_SCRIPT="python -m nose pyros_utils"
  matrix:
    # We are only interested in shadow-fixed compatibility here
    # - ROS_DISTRO="indigo"   ROS_REPO=ros-shadow-fixed
    - ROS_DISTRO="indigo"     ROS_REPO=ros-shadow-fixed
    # - ROS_DISTRO="indigo"   PRERELEASE=true
    # - ROS_DISTRO="kinetic"  ROS_REPO=ros-shadow-fixed
    - ROS_DISTRO="kinetic"    ROS_REPO=ros-shadow-fixed
    # - ROS_DISTRO="kinetic"  PRERELEASE=true
    # - ROS_DISTRO="lunar"    ROS_REPO=ros-shadow-fixed
    - ROS_DISTRO="lunar"      ROS_REPO=ros-shadow-fixed
    # - ROS_DISTRO="lunar"    PRERELEASE=true

matrix:
  allow_failures:
  # Run docker-based ROS prerelease test http://wiki.ros.org/bloom/Tutorials/PrereleaseTest
  # Because we might not want to run prerelease test for all PRs, it's omitted from pass-fail criteria.
    - env: ROS_DISTRO="indigo" PRERELEASE=true
    - env: ROS_DISTRO="kinetic"  PRERELEASE=true
    - env: ROS_DISTRO="lunar"  PRERELEASE=true

install:
  - git clone -b target-repo-rw https://github.com/ipa-mdl/industrial_ci.git .ci_config

script:
  - .ci_config/travis.sh

notifications:
  email: false

