# This config file for Travis CI utilizes ros-industrial/industrial_ci package.
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst
services:
  - docker
language: generic

branches:
  except:
   - gh-pages

env:
  global:
    - VERBOSE_OUTPUT=true
    - AFTER_SCRIPT="python -m nose pyros_utils"
  matrix:
    # We are only interested in shadow-fixed compatibility here
    - DOCKER_IMAGE=indigo-trusty-shadow-fixed
    - DOCKER_IMAGE=kinetic-xenial-shadow-fixed
    - DOCKER_IMAGE=lunar-xenial-shadow-fixed

install:
  - git clone -b target-repo-rw https://github.com/ipa-mdl/industrial_ci.git .ci_config

script:
  - .ci_config/travis.sh

notifications:
  email: false

